import type { TeacherHoursSession } from "./types";

// Presentation-only data. The feature view consumes this contract rather than embedding data in JSX.
// TODO(domain): attendance and session status are independent; do not derive one from the other.
export const teacherHoursMockSessions: TeacherHoursSession[] = [
  { id: "th-01", scheduledDate: "2026-09-21", classOrGroup: { id: "g-b1", name: "B1 Group" }, scheduled: { teacher: { id: "andre", name: "André Martins" }, startMinutes: 540, endMinutes: 600, durationMinutes: 60 }, actual: { teacher: { id: "andre", name: "André Martins" }, timeInClassMinutes: 57, attendance: "Present", sessionStatus: "Taught" }, classType: "original", flags: [], observations: null },
  { id: "th-02", scheduledDate: "2026-09-20", classOrGroup: { id: "g-a2", name: "A2 Group" }, scheduled: { teacher: { id: "mariana", name: "Mariana Costa" }, startMinutes: 600, endMinutes: 660, durationMinutes: 60 }, actual: { teacher: { id: "mariana", name: "Mariana Costa" }, timeInClassMinutes: 42, attendance: "Present", sessionStatus: "Taught" }, classType: "original", flags: ["Under minimum time"], observations: "Connection dropped before the final practice activity." },
  { id: "th-03", scheduledDate: "2026-09-19", classOrGroup: { id: "g-conversation", name: "Conversation Club" }, scheduled: { teacher: { id: "andre", name: "André Martins" }, startMinutes: 870, endMinutes: 930, durationMinutes: 60 }, actual: { teacher: { id: "rafael", name: "Rafael Okafor" }, timeInClassMinutes: 51, attendance: "Present", sessionStatus: "Taught" }, classType: "substitution", flags: ["Substitution requiring review"], observations: "Rafael covered the scheduled session." },
  { id: "th-04", scheduledDate: "2026-09-18", classOrGroup: { id: "individual-lucas", name: "Lucas Almeida" }, scheduled: { teacher: { id: "lucas", name: "Lucas Almeida" }, startMinutes: 1020, endMinutes: 1065, durationMinutes: 45 }, actual: { teacher: null, timeInClassMinutes: 0, attendance: "Absent", sessionStatus: "Scheduled" }, classType: "original", flags: ["Teacher absent", "Missing check-in"], observations: "Attendance source has not been reconciled." },
  { id: "th-05", scheduledDate: "2026-09-17", classOrGroup: { id: "g-b2", name: "B2 Group" }, scheduled: { teacher: { id: "mariana", name: "Mariana Costa" }, startMinutes: 1080, endMinutes: 1140, durationMinutes: 60 }, actual: { teacher: { id: "mariana", name: "Mariana Costa" }, timeInClassMinutes: 18, attendance: "Present", sessionStatus: "Taught" }, classType: "original", flags: ["Under minimum time", "Time discrepancy"], observations: "Session ended early after a platform issue." },
  { id: "th-06", scheduledDate: "2026-09-16", classOrGroup: { id: "g-a2", name: "A2 Group" }, scheduled: { teacher: { id: "andre", name: "André Martins" }, startMinutes: 510, endMinutes: 570, durationMinutes: 60 }, actual: { teacher: null, timeInClassMinutes: null, attendance: "No data", sessionStatus: "Canceled" }, classType: "original", flags: [], observations: "Canceled before the scheduled start." },
  { id: "th-07", scheduledDate: "2026-09-14", classOrGroup: { id: "g-b1", name: "B1 Group" }, scheduled: { teacher: { id: "mariana", name: "Mariana Costa" }, startMinutes: 540, endMinutes: 600, durationMinutes: 60 }, actual: { teacher: { id: "mariana", name: "Mariana Costa" }, timeInClassMinutes: null, attendance: "No data", sessionStatus: "Taught" }, classType: "original", flags: ["Missing data"], observations: null },
  { id: "th-08", scheduledDate: "2026-09-11", classOrGroup: { id: "g-conversation", name: "Conversation Club" }, scheduled: { teacher: { id: "lucas", name: "Lucas Almeida" }, startMinutes: 840, endMinutes: 900, durationMinutes: 60 }, actual: { teacher: { id: "andre", name: "André Martins" }, timeInClassMinutes: 55, attendance: "Present", sessionStatus: "Rescheduled" }, classType: "substitution", flags: [], observations: null },
  { id: "th-09", scheduledDate: "2026-09-08", classOrGroup: { id: "individual-ana", name: "Ana Ribeiro" }, scheduled: { teacher: { id: "andre", name: "André Martins" }, startMinutes: 1020, endMinutes: 1065, durationMinutes: 45 }, actual: { teacher: { id: "andre", name: "André Martins" }, timeInClassMinutes: 45, attendance: "Present", sessionStatus: "Taught" }, classType: "original", flags: [], observations: "Student requested additional pronunciation practice." },
  { id: "th-10", scheduledDate: "2026-08-30", classOrGroup: { id: "g-b2", name: "B2 Group" }, scheduled: { teacher: { id: "lucas", name: "Lucas Almeida" }, startMinutes: 1080, endMinutes: 1140, durationMinutes: 60 }, actual: { teacher: { id: "lucas", name: "Lucas Almeida" }, timeInClassMinutes: 52, attendance: "Present", sessionStatus: "Taught" }, classType: "original", flags: [], observations: null },
];
